/*
  # Deep Expanded Notes - Topic 3: Statistics and Probability
*/

DELETE FROM topic_sections WHERE topic_id = 'b1000001-0000-0000-0000-000000000003';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('b1000001-0000-0000-0000-000000000003',
'Concept Overview: Statistics and Probability',
E'## Statistics and Probability: The Science of Data and Chance\n\n**Statistics** is the science of collecting, organising, summarising, and interpreting data to make informed decisions. In everyday life, statistics are everywhere: opinion polls, weather forecasts, sports analytics, health studies.\n\n**Probability** is the mathematics of chance — quantifying how likely events are to occur, on a scale from 0 (impossible) to 1 (certain).\n\n**What you will learn:**\n- Measures of central tendency: Mean, Median, Mode — what they mean and when to use each\n- Measures of spread: Range, Variance, Standard Deviation, IQR\n- Working with frequency tables and grouped data\n- Drawing and reading statistical diagrams: histograms, bar charts, pie charts, cumulative frequency curves\n- Probability: basic rules, combined events, conditional probability\n- Counting methods: permutations and combinations\n\n**WASSCE Exam Pattern:**\nStatistics is one of the most reliably-tested areas in WASSCE. Every paper includes:\n- Calculation of mean, median, or mode from a table\n- A question on the cumulative frequency curve (ogive)\n- 1-2 probability questions\nExpect 15-25% of all marks to come from this topic.',
'overview', 1),

('b1000001-0000-0000-0000-000000000003',
'Definitions & Key Statistical Terms',
E'## Measures of Central Tendency\n\n**Mean (Arithmetic Average)**\nThe sum of all values divided by the number of values.\n`Mean (x̄) = (Sum of all values) / (Number of values) = Σx / n`\nThe mean uses ALL the data, so it is affected by extreme values (outliers).\n\n**Median**\nThe middle value when data is arranged in ascending order.\n- If n is odd: median is the ((n+1)/2)th value\n- If n is even: median is the average of the (n/2)th and ((n/2)+1)th values\nThe median is NOT affected by outliers, making it better for skewed data.\n\n**Mode**\nThe value(s) that appear most frequently in the data.\n- A dataset can be unimodal (one mode), bimodal (two modes), or multimodal\n- If all values appear equally often, there is NO mode\n\n## Measures of Spread (Dispersion)\n\n**Range**\n`Range = Maximum value - Minimum value`\nSimple but heavily influenced by extreme values.\n\n**Quartiles**\n- Q1 (Lower quartile): Value at 25th percentile — middle of lower half\n- Q2 (Median): Value at 50th percentile\n- Q3 (Upper quartile): Value at 75th percentile — middle of upper half\n\n**Interquartile Range (IQR)**\n`IQR = Q3 - Q1`\nThe range of the middle 50% of data. Resistant to outliers.\n\n**Variance**\nThe average of squared deviations from the mean.\n`Variance (σ²) = Σ(x - x̄)² / n`\nAlternative formula: `Variance = Σx²/n - (x̄)²`\n\n**Standard Deviation**\nThe square root of variance. Same units as original data.\n`σ = √Variance`\nLarger standard deviation means data is more spread out.\n\n## Probability Terms\n\n**Experiment**: Any process with an uncertain outcome (e.g., rolling a die, flipping a coin)\n\n**Sample Space (S)**: The set of ALL possible outcomes of an experiment.\n- Rolling a die: S = {1, 2, 3, 4, 5, 6}\n\n**Event**: Any subset of the sample space.\n- Getting an even number: E = {2, 4, 6}\n\n**Probability of an event**:\n`P(E) = Number of favourable outcomes / Total number of equally likely outcomes`\n\n**Certain event**: P = 1 (will definitely happen)\n**Impossible event**: P = 0 (cannot happen)\nFor any event: 0 ≤ P(E) ≤ 1\n\n**Mutually exclusive events**: Two events that CANNOT happen at the same time.\n- Rolling a 2 and rolling a 5 on the same die throw.\n\n**Independent events**: The occurrence of one does NOT affect the probability of the other.\n- Flipping a coin twice: each flip is independent.\n\n**Complementary event**: The event that E does NOT happen.\n`P(E does not happen) = 1 - P(E)`',
'definitions', 2),

('b1000001-0000-0000-0000-000000000003',
'Formulas, Rules & Deep Explanations',
E'## Mean from Frequency Table\n\nWhen data is presented in a frequency table:\n`Mean (x̄) = Σ(f × x) / Σf`\n\nwhere f = frequency of each value, x = the value itself.\n\n## Mean from Grouped Data (Class Intervals)\n\nWhen data is in class intervals (e.g., 0-9, 10-19, 20-29):\n1. Find the midpoint of each class: midpoint = (lower limit + upper limit) / 2\n2. Use mean formula: `x̄ = Σ(f × midpoint) / Σf`\n\n**Why midpoints?** We assume each value in a class is at the midpoint. This is an approximation, but it is standard practice.\n\n## Standard Deviation — Complete Method\n\n**Step-by-step for ungrouped data:**\n1. Calculate the mean (x̄)\n2. Subtract mean from each value: (x - x̄)\n3. Square each deviation: (x - x̄)²\n4. Find the average of squared deviations: Σ(x - x̄)² / n\n5. Take the square root\n\n**Shortcut formula**: `σ = √(Σx²/n - x̄²)`\n\n## Cumulative Frequency Curve (Ogive)\n\nA cumulative frequency table is built by adding up frequencies progressively.\n\n**Steps to draw an ogive:**\n1. Add a cumulative frequency column (running total)\n2. Plot points at the UPPER BOUNDARY of each class against cumulative frequency\n3. Join with a smooth S-curve\n4. The curve always starts at (lower bound of first class, 0)\n\n**Reading from an ogive:**\n- Median: Read at Σf/2 on y-axis → across to curve → down to x-axis\n- Q1: Read at Σf/4 on y-axis\n- Q3: Read at 3Σf/4 on y-axis\n- Percentile: Read at the appropriate fraction on y-axis\n\n## The Complete Probability Rules\n\n**Rule 1 — Complementary Events**:\n`P(A does not occur) = 1 - P(A)`\n\n**Rule 2 — Mutually Exclusive Events (OR)**:\nIf A and B CANNOT happen together:\n`P(A or B) = P(A) + P(B)`\n\n**Rule 3 — General Addition Rule**:\nFor ANY two events:\n`P(A or B) = P(A) + P(B) - P(A and B)`\n\n**Rule 4 — Independent Events (AND)**:\nIf A and B are independent:\n`P(A and B) = P(A) × P(B)`\n\n**Rule 5 — Conditional Probability**:\n`P(A | B) = P(A and B) / P(B)`\n(Read as "probability of A given that B has occurred")\n\n**Rule 6 — Without Replacement**:\nWhen drawing without replacement, the sample space changes after each draw.\nAfter drawing one item, the total decreases by 1 AND the count of that type decreases by 1.\n\n## Permutations and Combinations\n\n**Permutation** — arrangement where ORDER MATTERS:\n`nPr = n! / (n-r)!`\n\n**Combination** — selection where ORDER DOES NOT MATTER:\n`nCr = n! / [r!(n-r)!]`\n\n**Factorial**: `n! = n × (n-1) × (n-2) × ... × 2 × 1`\n`0! = 1` (by definition)',
'explanation', 3),

('b1000001-0000-0000-0000-000000000003',
'Worked Examples — Data, Graphs & Probability',
E'## PART 1: Measures of Central Tendency\n\n### Example 1.1: Mean, Median, Mode from raw data\n**Data: 3, 7, 5, 9, 7, 4, 7, 8, 5, 10**\n\nFirst, arrange in order: 3, 4, 5, 5, 7, 7, 7, 8, 9, 10\nn = 10\n\n**Mean**: Σx = 3+4+5+5+7+7+7+8+9+10 = 65\nMean = 65/10 = **6.5**\n\n**Median**: n=10 (even), so median = average of 5th and 6th values\n5th value = 7, 6th value = 7\nMedian = (7+7)/2 = **7**\n\n**Mode**: 7 appears 3 times (most frequent)\nMode = **7**\n\n### Example 1.2: Mean from Frequency Table\n\n| Score (x) | Frequency (f) | f × x |\n|-----------|--------------|-------|\n| 10 | 3 | 30 |\n| 20 | 5 | 100 |\n| 30 | 8 | 240 |\n| 40 | 4 | 160 |\n| 50 | 2 | 100 |\n| Total | 22 | 630 |\n\nMean = 630 / 22 = **28.6** (to 3 s.f.)\n\n### Example 1.3: Mean from Grouped Data\n\n| Class | Frequency | Midpoint | f × x |\n|-------|-----------|----------|-------|\n| 10-19 | 5 | 14.5 | 72.5 |\n| 20-29 | 12 | 24.5 | 294 |\n| 30-39 | 8 | 34.5 | 276 |\n| 40-49 | 5 | 44.5 | 222.5 |\n| Total | 30 | — | 865 |\n\nMean = 865 / 30 = **28.8** (to 3 s.f.)\n\n---\n\n## PART 2: Standard Deviation\n\n### Example 2.1\n**Data: 2, 4, 4, 6, 8, 10**\n\nMean = (2+4+4+6+8+10)/6 = 34/6 ≈ 5.67\n\n| x | x - x̄ | (x - x̄)² |\n|---|--------|----------|\n| 2 | -3.67 | 13.47 |\n| 4 | -1.67 | 2.79 |\n| 4 | -1.67 | 2.79 |\n| 6 | 0.33 | 0.11 |\n| 8 | 2.33 | 5.43 |\n| 10 | 4.33 | 18.75 |\n| Total | 0 | 43.33 |\n\nVariance = 43.33/6 = 7.22\nStandard Deviation = √7.22 ≈ **2.69**\n\n---\n\n## PART 3: Probability\n\n### Example 3.1: Basic Probability\n**A bag contains 5 red, 3 blue, 2 green balls. One is drawn at random.**\n\nTotal = 10\nP(red) = 5/10 = 1/2\nP(blue) = 3/10\nP(green) = 2/10 = 1/5\nP(not red) = 1 - 1/2 = 1/2\n\n### Example 3.2: Without Replacement (WASSCE Type)\n**A box has 4 red and 6 blue balls. Two balls are drawn WITHOUT replacement. Find P(both red).**\n\nP(1st red) = 4/10 = 2/5\nP(2nd red | 1st was red) = 3/9 = 1/3 (one less red and one less total)\n\nP(both red) = (2/5) × (1/3) = **2/15**\n\n### Example 3.3: Combined Events\n**P(A) = 0.4, P(B) = 0.5, P(A and B) = 0.2. Find P(A or B).**\n\nGeneral addition rule:\nP(A or B) = P(A) + P(B) - P(A and B)\nP(A or B) = 0.4 + 0.5 - 0.2 = **0.7**\n\n### Example 3.4: Combinations\n**A committee of 3 is to be chosen from 6 men and 4 women. Find the number of ways to choose exactly 2 women.**\n\nChoose 2 women from 4: C(4,2) = 4!/(2!2!) = 6 ways\nChoose 1 man from 6: C(6,1) = 6 ways\n\nTotal ways = 6 × 6 = **36 ways**',
'examples', 4),

('b1000001-0000-0000-0000-000000000003',
'Common Mistakes + Practice Questions',
E'## Common Mistakes in Statistics\n\n**Mistake 1**: Using incorrect midpoints for class intervals.\n- For class 10-19: midpoint = (10+19)/2 = 14.5 (NOT 15)\n- For class 10-20: midpoint = (10+20)/2 = 15\n\n**Mistake 2**: "With replacement" vs "Without replacement" in probability.\n- WITHOUT replacement: total decreases by 1 each draw. Adjust carefully.\n\n**Mistake 3**: Adding instead of multiplying for AND events.\n- For independent AND events: MULTIPLY probabilities\n- For mutually exclusive OR events: ADD probabilities\n\n**Mistake 4**: Forgetting that P(A or B) = P(A) + P(B) - P(A and B).\n- The general formula must be used when events are NOT mutually exclusive.\n\n**Mistake 5**: Reading cumulative frequency at the midpoint instead of upper boundary.\n- Plot cumulative frequency at the UPPER CLASS BOUNDARY.\n\n**Mistake 6**: Standard deviation is in the SAME units as data.\n- Variance is in squared units. Standard deviation restores the original units.\n\n---\n\n## Practice Questions\n\n### Section A: Objective\n\n**Q1:** Mean of 5, 8, 11, 14, 17 =?\n(A) 10   (B) 11   (C) 12   (D) 13\n\n**Q2:** If P(A) = 0.6 and A and B are independent with P(B) = 0.4, then P(A and B) =?\n(A) 0.24   (B) 1.0   (C) 0.76   (D) 0.2\n\n**Q3:** Median of: 3, 3, 5, 7, 7, 8, 9, 11 =?\n(A) 5   (B) 6   (C) 7   (D) 7.5\n\n### Section B: Theory\n\n**Q4:** The table shows scores (x) with frequencies: x=1 (f=2), x=2 (f=5), x=3 (f=8), x=4 (f=4), x=5 (f=1). Calculate: (a) mean (b) mode (c) median.\n\n**Q5:** Two dice are thrown. Find P(sum = 7) and P(sum = 11).\n\n**Q6:** Data: 4, 6, 8, 10, 12. Calculate the standard deviation.\n\n### Section C: Exam Standard\n\n**Q7:** A box contains 3 red, 4 green, 5 blue counters. Two counters are drawn without replacement. Find: (a) P(both same colour) (b) P(at least one red)\n\n---\n\n## Solutions\n\n**Q1:** (5+8+11+14+17)/5 = 55/5 = 11 → **(B)**\n\n**Q2:** 0.6 × 0.4 = 0.24 → **(A)**\n\n**Q3:** n=8, median = average of 4th and 5th values = (7+7)/2 = 7 → **(C)**\n\n**Q4:**\n(a) Σf = 20, Σfx = 2+10+24+16+5 = 57, mean = 57/20 = 2.85\n(b) Mode = 3 (highest frequency, f=8)\n(c) Median: 10th and 11th values. Cumulative: 2,7,15... so both fall in x=3. Median = 3\n\n**Q5:** Sample space = 36. Pairs summing to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 pairs. P(7) = 6/36 = 1/6. Pairs summing to 11: (5,6),(6,5) = 2. P(11) = 2/36 = 1/18.\n\n**Q6:** Mean = (4+6+8+10+12)/5 = 8. Deviations: -4,-2,0,2,4. Squared: 16,4,0,4,16. Sum=40. Variance=8. SD=√8=2√2≈2.83\n\n**Q7:** Total = 12. (a) P(both red)=3/12×2/11=6/132; P(both green)=4/12×3/11=12/132; P(both blue)=5/12×4/11=20/132. P(same colour)=38/132=19/66. (b) P(at least one red) = 1 - P(no red) = 1 - (9/12 × 8/11) = 1 - 72/132 = 60/132 = 5/11.',
'practice', 5);
