/*
  # Expand Deep Notes: Topics 14, 15, 16, 17
  
  Topic 14: Linear Graphs and Relations
  Topic 15: Quadratic Equations and Functions
  Topic 16: Variation (Direct, Inverse, Joint)
  Topic 17: Construction and Loci
*/

-- TOPIC 14: Linear Graphs
DELETE FROM topic_sections WHERE topic_id = 'a1ddc835-a1ef-4db3-99be-194e1af0353e';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('a1ddc835-a1ef-4db3-99be-194e1af0353e',
'Concept Overview: Linear Graphs and Relations',
E'## What Are Linear Graphs?\n\nA linear graph is a straight line on a coordinate plane. The word "linear" means relating to a line. Any equation of the form y = mx + c produces a straight line when graphed.\n\nIn WASSCE, linear graphs appear in questions worth 6-10 marks and connect to real-world modelling.\n\n### The General Form\n\n**y = mx + c** (slope-intercept form)\n- m = gradient (slope) — how steep the line is\n- c = y-intercept — where the line crosses the y-axis\n\n**ax + by = k** (standard form) — both variables on one side\n\n### Key Concepts\n\n1. Drawing straight line graphs from tables of values\n2. Finding gradient from a graph (rise over run)\n3. Finding equations from graphs\n4. Interpreting distance-time and speed-time graphs\n5. Using graphs to solve simultaneous linear equations\n6. Drawing and interpreting linear inequalities\n\n### Real-World Linear Relationships\n\n- Distance = Speed x Time (constant speed gives straight line)\n- Total cost = Fixed cost + (Variable cost per unit x Quantity)\n- Temperature conversion: F = (9/5)C + 32\n- Exchange rates: Y = kX (through origin)',
'overview', 1),

('a1ddc835-a1ef-4db3-99be-194e1af0353e',
'Definitions and Methods for Linear Graphs',
E'## Key Definitions and Procedures\n\n### Gradient\n\nGradient m = (change in y)/(change in x) = (y2-y1)/(x2-x1)\n\nFrom a graph: choose two clear points on the line, draw the right-angle triangle, measure vertical rise and horizontal run.\n\nm = rise/run\n\n**Positive gradient**: line rises left to right\n**Negative gradient**: line falls left to right\n**Zero gradient**: horizontal line\n**Undefined**: vertical line\n\n### Drawing Linear Graphs\n\nMethod 1 — Table of values:\n1. Choose 3-5 x values (include negatives and zero)\n2. Substitute into equation to find y values\n3. Plot the (x, y) pairs\n4. Join with a straight line and extend\n5. Label the line with its equation\n\nMethod 2 — Intercept method:\n1. Set x = 0 to find y-intercept: (0, c)\n2. Set y = 0 to find x-intercept: (-c/m, 0)\n3. Plot both intercepts and join\n\n### Reading Graphs\n\n**To solve simultaneous equations graphically**: Draw both lines on the same axes. The intersection point is the solution.\n\n**Distance-time graphs**:\n- Gradient = speed\n- Horizontal line = stationary (stopped)\n- Steeper line = faster speed\n- Negative gradient = returning\n\n**Speed-time graphs**:\n- Gradient = acceleration\n- Horizontal line = constant speed\n- Area under graph = distance\n\n### Linear Inequalities on a Graph\n\nFor y > mx + c: shade ABOVE the line (use dashed line since y is not equal to mx+c)\nFor y < mx + c: shade BELOW the line\nFor y >= mx + c: shade above (use solid line)\nFor y <= mx + c: shade below (solid line)\n\nFor multiple inequalities, the solution is the region satisfying ALL conditions.',
'definitions', 2),

('a1ddc835-a1ef-4db3-99be-194e1af0353e',
'Worked Examples and Practice: Linear Graphs',
E'## Worked Examples\n\n### Example 1: Draw y = 2x - 1 for -2 <= x <= 3\n\nTable of values:\nx: -2, -1, 0, 1, 2, 3\ny = 2x-1: -5, -3, -1, 1, 3, 5\n\nPoints: (-2,-5), (-1,-3), (0,-1), (1,1), (2,3), (3,5)\nGradient = 2, y-intercept = -1\n\n### Example 2: Find equation from gradient 3 and point (2, 7)\n\ny - 7 = 3(x - 2)\ny = 3x - 6 + 7\ny = 3x + 1\n\n### Example 3: Solve graphically: y = x + 2 and y = -x + 6\n\nLine 1: y = x+2 passes through (0,2) and (2,4)\nLine 2: y = -x+6 passes through (0,6) and (6,0)\n\nIntersection: x+2 = -x+6; 2x = 4; x = 2, y = 4\nSolution: (2, 4)\n\n### Example 4: Distance-time interpretation\nA car travels for 2 hours covering 120 km, stops for 1 hour, then returns 90 km in 1.5 hours.\n\nSpeeds:\n- Outward: 120/2 = 60 km/h\n- Stopped: 0 km/h\n- Return: 90/1.5 = 60 km/h (negative gradient showing return)\n\n---\n\n## Practice Questions\n\n**Q1**: Complete the table for y = 3x - 4 and draw the graph:\nx: -1, 0, 1, 2, 3\n\n**Q2**: From the graph of 2x + y = 8, find where the line crosses both axes.\n\n**Q3**: A taxi charges a fixed fee of GH₵5 plus GH₵2 per km. Write a linear equation and find the fare for 12 km.\n\n**Q4**: Two lines: L1: y = 2x + 1 and L2: y = -x + 7. Find their intersection algebraically and verify graphically.\n\n---\n\n## Solutions\n\n**Q1**: y values: -7, -4, -1, 2, 5\n\n**Q2**: x-intercept: set y=0: 2x=8, x=4. Point (4,0). y-intercept: set x=0: y=8. Point (0,8).\n\n**Q3**: C = 5 + 2d; For d=12: C = 5 + 24 = GH₵29\n\n**Q4**: 2x+1 = -x+7; 3x = 6; x=2; y=5. Intersection: (2, 5)',
'explanation', 3),

('a1ddc835-a1ef-4db3-99be-194e1af0353e',
'Common Mistakes & Exam-Standard Practice',
E'## Common Mistakes\n\n1. **Plotting errors**: Always use a ruler. A slight curve suggests a calculation error — check your table of values.\n\n2. **Reading gradient from graph incorrectly**: Choose points that are ON the line, not just near it. Use clearly readable grid points.\n\n3. **Forgetting to extend the line**: A graph should show the line extending beyond the plotted points (with arrows indicating it continues).\n\n4. **Inequality region confusion**: For y > mx + c, shade above. A quick test: pick a point clearly above the line (e.g., (0, 100)) and check if it satisfies the inequality.\n\n5. **Distance-time graph misreading**: The gradient (not the height) represents speed. A tall point means far away, not moving fast.\n\n---\n\n## Exam-Standard Questions\n\n**Question 1**: Draw the graph of y = (1/2)x + 3 for -4 <= x <= 4. From your graph:\n(a) Find the gradient\n(b) Find y when x = 3\n(c) Find x when y = 5\n\n**Question 2**: On the same axes, draw: y = 2x - 1 and x + y = 5. Find the intersection point.\n\n**Question 3**: A phone company charges GH₵20/month plus GH₵0.50 per minute.\n(a) Write the cost equation.\n(b) Draw the graph for 0 to 60 minutes.\n(c) At what usage do two companies with charges C1 = 20 + 0.5m and C2 = 35 + 0.25m charge the same amount?\n\n---\n\n## Solutions\n\n**Q1**: (a) Gradient = 1/2 (read from graph: rise 1, run 2)\n(b) y = (1/2)(3) + 3 = 4.5\n(c) 5 = (1/2)x + 3; (1/2)x = 2; x = 4\n\n**Q2**: From 2x-1 = -x+5; 3x = 6; x=2, y=3. Intersection: (2,3)\n\n**Q3**: (a) C = 20 + 0.5m\n(b) At m=0: C=20; at m=60: C=50\n(c) 20+0.5m = 35+0.25m; 0.25m = 15; m = 60 minutes',
'practice', 4);


-- TOPIC 15: Quadratic Equations
DELETE FROM topic_sections WHERE topic_id = 'd8bf5bf6-525f-4a57-8f2e-1963651e5d7a';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('d8bf5bf6-525f-4a57-8f2e-1963651e5d7a',
'Concept Overview: Quadratic Equations and Functions',
E'## What Are Quadratic Equations?\n\nA quadratic equation has the general form **ax^2 + bx + c = 0** where a is not 0.\n\nThe graph of a quadratic function y = ax^2 + bx + c is called a **parabola**.\n\nIn WASSCE, quadratics carry 8-12 marks and appear in theory questions on solving, graphing, and word problems.\n\n### Four Methods of Solution\n\n1. **Factorisation** — fastest when possible\n2. **Completing the square** — useful for finding vertex\n3. **Quadratic formula** — always works\n4. **Graphical method** — find x-intercepts of the parabola\n\n### Nature of Roots\n\nThe **discriminant** D = b^2 - 4ac tells us:\n- D > 0: Two distinct real roots\n- D = 0: One repeated real root (touches x-axis)\n- D < 0: No real roots (parabola misses x-axis)\n\n### Key Applications\n\n- Projectile motion (ball thrown in air)\n- Area problems (find dimensions given area)\n- Revenue maximisation in business\n- Geometric problems (finding lengths)',
'overview', 1),

('d8bf5bf6-525f-4a57-8f2e-1963651e5d7a',
'All Methods for Solving Quadratics',
E'## Method 1: Factorisation\n\nFor ax^2 + bx + c = 0:\n1. Find two numbers that MULTIPLY to give ac and ADD to give b\n2. Rewrite the middle term using these numbers\n3. Factor by grouping\n4. Set each factor to zero and solve\n\n**Example**: Solve x^2 - 7x + 12 = 0\nFind numbers multiplying to 12, adding to -7: -3 and -4\n(x - 3)(x - 4) = 0\nx = 3 or x = 4\n\n**Example**: Solve 2x^2 + 5x - 3 = 0\nac = 2x(-3) = -6; find numbers giving -6 and +5: +6 and -1\n2x^2 + 6x - x - 3 = 0\n2x(x + 3) - 1(x + 3) = 0\n(2x - 1)(x + 3) = 0\nx = 1/2 or x = -3\n\n## Method 2: Quadratic Formula\n\nx = [-b +/- sqrt(b^2 - 4ac)] / (2a)\n\nThis formula works for ANY quadratic. Use it when factorisation is not obvious or when exact decimal answers are needed.\n\n**Example**: Solve 3x^2 - 5x + 1 = 0\na=3, b=-5, c=1\nD = 25 - 12 = 13\nx = (5 +/- sqrt(13)) / 6\nx = (5 + 3.606)/6 = 1.434 or x = (5 - 3.606)/6 = 0.232\n\n## Method 3: Completing the Square\n\nFor x^2 + bx + c = 0:\n1. Move c to right side\n2. Add (b/2)^2 to both sides\n3. Write left side as (x + b/2)^2\n4. Square root both sides\n5. Solve for x\n\n**Example**: Solve x^2 + 6x - 7 = 0 by completing the square\nx^2 + 6x = 7\nx^2 + 6x + 9 = 7 + 9 = 16\n(x + 3)^2 = 16\nx + 3 = +/-4\nx = 1 or x = -7\n\n## Sum and Product of Roots\n\nFor ax^2 + bx + c = 0 with roots p and q:\n- Sum: p + q = -b/a\n- Product: p x q = c/a\n\nUseful for forming equations with given roots:\nIf roots are p and q: x^2 - (p+q)x + (pq) = 0',
'definitions', 2),

('d8bf5bf6-525f-4a57-8f2e-1963651e5d7a',
'Worked Examples and Practice: Quadratics',
E'## Worked Examples\n\n### Example 1: Solve x^2 - 5x + 6 = 0\nFactors: (x-2)(x-3) = 0\nx = 2 or x = 3\n\n### Example 2: Solve 2x^2 - x - 6 = 0 using the formula\na=2, b=-1, c=-6\nD = 1 + 48 = 49\nx = (1 +/- 7)/4\nx = 8/4 = 2 or x = -6/4 = -3/2\n\n### Example 3: Find k if x=3 is a root of x^2 - kx + 6 = 0\nSubstitute x=3: 9 - 3k + 6 = 0; 15 = 3k; k = 5\n\n### Example 4: The sum of a number and its reciprocal is 10/3. Find the number.\nLet number = x. Then x + 1/x = 10/3\n3x^2 + 3 = 10x\n3x^2 - 10x + 3 = 0\n(3x - 1)(x - 3) = 0\nx = 1/3 or x = 3\n\n### Example 5: A rectangle has length 3 more than its width, and area 180 cm2. Find dimensions.\nLet width = x. Length = x+3.\nx(x+3) = 180\nx^2 + 3x - 180 = 0\n(x + 15)(x - 12) = 0\nx = 12 (reject x = -15 since dimension must be positive)\nWidth = 12 cm, Length = 15 cm\n\n---\n\n## Practice Questions\n\n**Q1**: Solve by factorisation: 6x^2 + 7x - 3 = 0\n\n**Q2**: Use the quadratic formula to solve: x^2 + 4x - 2 = 0 (give answers to 2 d.p.)\n\n**Q3**: If the roots of x^2 + px + 12 = 0 are 3 and q, find p and q.\n\n**Q4**: Find the range of values of m for which 4x^2 - mx + 9 = 0 has real roots.\n\n---\n\n## Solutions\n\n**Q1**: ac = -18; numbers: +9 and -2\n6x^2 + 9x - 2x - 3 = 0\n3x(2x+3) - 1(2x+3) = 0\n(3x-1)(2x+3) = 0\nx = 1/3 or x = -3/2\n\n**Q2**: D = 16+8 = 24; x = (-4 +/- sqrt(24))/2 = (-4 +/- 4.899)/2\nx = 0.45 or x = -4.45\n\n**Q3**: Sum = 3+q = -p; Product = 3q = 12; q=4; p = -(3+4) = -7\n\n**Q4**: Discriminant >= 0: m^2 - 4(4)(9) >= 0; m^2 >= 144; m <= -12 or m >= 12',
'explanation', 3),

('d8bf5bf6-525f-4a57-8f2e-1963651e5d7a',
'Common Mistakes & Quadratic Graphs',
E'## Common Mistakes\n\n1. **Not setting equation to zero**: Before factorising or using the formula, always rearrange so one side is zero.\n\n2. **Wrong signs in factorisation**: Check by expanding your factors back. (x-2)(x+3) gives x^2 + x - 6, not x^2 - x - 6.\n\n3. **Forgetting +/- in square root**: When completing the square, (x+3)^2 = 16 gives x+3 = +4 OR x+3 = -4. Both solutions must be found.\n\n4. **Rejecting valid negative roots**: In purely algebraic problems, negative roots are valid. Only reject them in practical problems where negatives make no physical sense (lengths, times, quantities).\n\n5. **Discriminant sign error**: D = b^2 - 4ac. For 3x^2 - 5x + 1, a=3, b=-5, c=1: D = (-5)^2 - 4(3)(1) = 25-12 = 13.\n\n---\n\n## Quadratic Graphs (Parabolas)\n\nFor y = ax^2 + bx + c:\n- If a > 0: parabola opens upward (U-shape), minimum point\n- If a < 0: parabola opens downward (hill-shape), maximum point\n- Vertex (turning point): x = -b/(2a); substitute to find y\n- Axis of symmetry: x = -b/(2a)\n- x-intercepts: where y = 0 (solve quadratic)\n- y-intercept: where x = 0, y = c\n\n## Exam-Standard Questions\n\n**Question 1**: Draw the graph of y = x^2 - 4x + 3 for -1 <= x <= 5.\n(a) State the roots of x^2 - 4x + 3 = 0\n(b) Find the minimum value and where it occurs\n(c) Find y when x = 3.5\n\n**Question 2**: The height h metres of a ball after t seconds is h = 20t - 5t^2.\n(a) Find when the ball returns to ground level\n(b) Find the maximum height reached\n\n---\n\n## Solutions\n\n**Q1**: Table: x(-1,0,1,2,3,4,5) → y(8,3,0,-1,0,3,8)\n(a) Roots: x = 1 and x = 3 (where y = 0)\n(b) Vertex: x = -(-4)/(2x1) = 2; y = 4-8+3 = -1. Minimum = -1 at x = 2\n(c) y = 12.25 - 14 + 3 = 1.25\n\n**Q2**:\n(a) 20t - 5t^2 = 0; 5t(4-t) = 0; t = 0 or t = 4 seconds\n(b) Max at t = 2: h = 40 - 20 = 20 metres',
'practice', 4);


-- TOPIC 16: Variation
DELETE FROM topic_sections WHERE topic_id = '8a29a189-176a-4e3b-88b4-3b1c05592ab7';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('8a29a189-176a-4e3b-88b4-3b1c05592ab7',
'Concept Overview and Definitions: Variation',
E'## What Is Variation?\n\nVariation describes how one quantity changes in relation to another. In WASSCE, this topic carries 4-8 marks and is highly predictable.\n\n### Types of Variation\n\n**Direct Variation**: y varies directly as x means y = kx\n- As x increases, y increases proportionally\n- Graph: straight line through origin\n- k = y/x (constant ratio)\n\n**Inverse Variation**: y varies inversely as x means y = k/x\n- As x increases, y decreases\n- Graph: hyperbola\n- k = xy (constant product)\n\n**Joint Variation**: y varies jointly as x and z means y = kxz\n- y is directly proportional to BOTH x and z\n\n**Partial Variation**: y = ax + b (varies partly as x and partly constant)\n\n**Combined Variation**: y varies directly as x and inversely as z: y = kx/z\n\n## The Constant of Variation\n\nThe constant k is found by substituting known values.\n\n**Method**:\n1. Write the variation equation (with k)\n2. Substitute known values\n3. Solve for k\n4. Use k to solve the problem\n\n## Key Worked Examples\n\n### Direct: y is directly proportional to x^2. When x=3, y=36. Find y when x=5.\ny = kx^2; 36 = k(9); k = 4\ny = 4x^2; when x=5: y = 4(25) = 100\n\n### Inverse: y varies inversely as sqrt(x). When x=4, y=6. Find y when x=9.\ny = k/sqrt(x); 6 = k/2; k = 12\ny = 12/sqrt(9) = 12/3 = 4\n\n### Joint: z varies jointly as x and y^2. When x=2, y=3, z=72. Find z when x=5, y=4.\nz = kxy^2; 72 = k(2)(9); k = 4\nz = 4(5)(16) = 320\n\n## Practice Questions\n\n**Q1**: p varies directly as the square of q. When q=5, p=75. Find p when q=8.\n\n**Q2**: V varies inversely as P. When P=4, V=15. Find V when P=10, and find P when V=6.\n\n**Q3**: T varies jointly as m and the square root of n. When m=4 and n=9, T=24. Find T when m=6, n=16.\n\n**Q4**: y varies partly as x and partly as x^2. When x=1, y=5 and when x=2, y=14. Find y when x=5.\n\n## Solutions\n\n**Q1**: p = kq^2; 75 = 25k; k=3; p = 3(64) = 192\n\n**Q2**: V = k/P; 15 = k/4; k=60; V = 60/10 = 6; P = 60/6 = 10\n\n**Q3**: T = k*m*sqrt(n); 24 = k(4)(3); k=2; T = 2(6)(4) = 48\n\n**Q4**: y = ax + bx^2\nWhen x=1: a + b = 5 ...(i)\nWhen x=2: 2a + 4b = 14 → a + 2b = 7 ...(ii)\nSubtract: b=2; a=3\ny = 3(5) + 2(25) = 15 + 50 = 65',
'overview', 1),

('8a29a189-176a-4e3b-88b4-3b1c05592ab7',
'Deep Explanation and Worked Problems: Variation',
E'## Recognising Variation Type\n\nThe problem statement uses specific language:\n\n| Statement | Equation form |\n| y varies directly as x | y = kx |\n| y varies as x squared | y = kx^2 |\n| y varies inversely as x | y = k/x |\n| y is inversely proportional to x^2 | y = k/x^2 |\n| y varies jointly as x and z | y = kxz |\n| y varies directly as x, inversely as z | y = kx/z |\n\n## Partial Variation — Detailed Explanation\n\nIn partial variation, one quantity is part constant and part variable:\ny = a + bx (partly constant, partly varies with x)\ny = ax + bx^2 (partly direct, partly square)\n\n**Strategy**: Two unknowns (a and b) require two equations. Use two given conditions.\n\n**Example**: The cost C of producing x items is partly fixed and partly varies with x. It costs GH₵500 to produce 10 items and GH₵800 to produce 25 items. Find the cost of producing 50 items.\n\nC = a + bx\n500 = a + 10b ...(i)\n800 = a + 25b ...(ii)\n(ii)-(i): 300 = 15b; b = 20\na = 500 - 200 = 300\nC = 300 + 20x\nCost of 50 items = 300 + 20(50) = GH₵1,300\n\n## Connection to Real Life\n\n**Ohm Law**: V = IR (V varies directly as I, with R constant)\n**Newton Law of Gravitation**: F = Gm1m2/d^2 (F varies as product of masses, inversely as d squared)\n**Boyle Law**: PV = constant (P varies inversely as V at constant temperature)\n\n## Tricky Exam Questions\n\nSometimes variation involves three variables:\n\n**Example**: Q varies directly as the square root of P and inversely as R. When P=25 and R=2, Q=20. Find Q when P=64, R=4.\n\nQ = k*sqrt(P)/R\n20 = k*5/2; k = 8\nQ = 8*sqrt(64)/4 = 8*8/4 = 16',
'definitions', 2),

('8a29a189-176a-4e3b-88b4-3b1c05592ab7',
'Practice Questions & Solutions: Variation',
E'## Additional Practice\n\n**Question 1**: The electrical resistance R of a wire varies directly as its length L and inversely as the square of its diameter d. A wire of length 100 m and diameter 0.5 cm has resistance 4 ohms. Find the resistance of a wire of length 75 m and diameter 0.3 cm.\n\n**Question 2**: Given that y varies partly as x and partly as the cube of x. When x=2, y=22 and when x=3, y=60. Find y when x=4.\n\n**Question 3 (WASSCE style)**: y is inversely proportional to (x+1)^2. When x=2, y=4. Find:\n(a) The constant of variation\n(b) y when x=4\n(c) x when y=1/4\n\n---\n\n## Full Solutions\n\n**Q1**: R = kL/d^2; 4 = k(100)/(0.25); k = 4x0.25/100 = 0.01\nR = 0.01(75)/(0.09) = 0.75/0.09 = 8.33 ohms\n\n**Q2**: y = ax + bx^3\nWhen x=2: 2a + 8b = 22 → a + 4b = 11 ...(i)\nWhen x=3: 3a + 27b = 60 → a + 9b = 20 ...(ii)\n(ii)-(i): 5b = 9; b = 1.8; a = 11 - 7.2 = 3.8\ny = 3.8(4) + 1.8(64) = 15.2 + 115.2 = 130.4\n\n**Q3**: y = k/(x+1)^2\n(a) 4 = k/(3)^2 = k/9; k = 36\n(b) y = 36/(4+1)^2 = 36/25 = 1.44\n(c) 1/4 = 36/(x+1)^2; (x+1)^2 = 144; x+1 = 12; x = 11',
'explanation', 3),

('8a29a189-176a-4e3b-88b4-3b1c05592ab7',
'Common Mistakes & Final Review: Variation',
E'## Common Mistakes\n\n1. **Forgetting to find k**: Always find the constant k before solving for the unknown. This is the most common mistake — students skip the "find k" step.\n\n2. **Using addition instead of multiplication for joint variation**: Joint variation is y = kxz (multiplication), NOT y = k(x+z).\n\n3. **Partial variation setup**: y = a + bx (not y = bx alone). The "partly constant" means there is a non-zero additive term.\n\n4. **Inverse with squared terms**: "Inversely as x^2" means y = k/x^2. Students sometimes write y = k/(x^2) correctly but then make errors squaring negative x values.\n\n5. **Equation mismatch**: When three quantities vary together, set up the full equation with ALL the variables, not just two of them.\n\n---\n\n## Summary Review Questions\n\n**Q1**: p is directly proportional to q^2 - 1. When q = 2, p = 6. Find p when q = 4, and q when p = 54.\n\n**Q2**: The time T taken to dig a trench varies directly as its length L and inversely as the number of workers W. 5 workers dig a 30 m trench in 6 days. How many workers are needed to dig a 45 m trench in 5 days?\n\n---\n\n## Solutions\n\n**Q1**: p = k(q^2-1); 6 = k(4-1) = 3k; k=2\nWhen q=4: p = 2(16-1) = 30\nWhen p=54: 54 = 2(q^2-1); q^2-1=27; q^2=28; q = sqrt(28) = 2sqrt(7) approx 5.29\n\n**Q2**: T = kL/W; 6 = k(30)/5; k = 1\nT = L/W; 5 = 45/W; W = 9 workers',
'practice', 4);


-- TOPIC 17: Construction and Loci
DELETE FROM topic_sections WHERE topic_id = 'f09042df-d7a9-46d8-98e9-1a82b5bd8892';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('f09042df-d7a9-46d8-98e9-1a82b5bd8892',
'Concept Overview: Construction and Loci',
E'## What Is Construction?\n\nGeometric construction means drawing exact geometric figures using only a compass and a straightedge (ungraduated ruler). No measurements are allowed.\n\nIn WASSCE, construction and loci appear in the theory paper, typically carrying 10-15 marks for a single multi-part question.\n\n### Essential Constructions to Master\n\n1. Perpendicular bisector of a line segment\n2. Perpendicular from a point to a line\n3. Perpendicular at a point on a line\n4. Angle bisector\n5. Angles of 60°, 30°, 90°, 45°, 120°, 75°, 105°\n6. Copy an angle\n7. Divide a line into equal parts\n8. Circumscribe and inscribe circles\n\n## What Is a Locus?\n\nA **locus** (plural: loci) is the set of ALL positions satisfying a given condition.\n\n**Key loci to know**:\n- Points equidistant from a fixed point → Circle\n- Points equidistant from two fixed points → Perpendicular bisector\n- Points equidistant from two lines → Angle bisector\n- Points at fixed distance from a line → Two parallel lines\n- Points equidistant from two parallel lines → Line midway between them',
'overview', 1),

('f09042df-d7a9-46d8-98e9-1a82b5bd8892',
'All Key Constructions Step-by-Step',
E'## Step-by-Step Constructions\n\n### 1. Perpendicular Bisector of AB\n\n1. Open compass to more than half of AB\n2. With centre A, draw arcs above and below AB\n3. With same radius, centre B, draw arcs crossing the first pair\n4. Join the two intersection points — this is the perpendicular bisector\n\nThis line is perpendicular to AB AND passes through its midpoint.\n\n### 2. Bisecting an Angle ABC\n\n1. Place compass at B, draw arc cutting BA at P and BC at Q\n2. With same radius from P and Q, draw arcs that intersect at R\n3. Draw ray BR — this is the angle bisector\n\n### 3. Constructing 60 degrees\n\n1. Draw a line and mark point A\n2. Open compass to any radius r\n3. With centre A, draw arc cutting the line at B\n4. With same radius from B, mark point C on the arc\n5. Angle BAC = 60°\n\n### 4. Constructing 90 degrees\n\nMethod: Bisect a straight angle (180°)\n1. Mark a point P on a line\n2. With centre P, draw equal arcs on both sides at A and B\n3. With centre A and B, draw arcs above intersecting at Q\n4. PQ is perpendicular to AB\n\n### 5. Constructing 30 and 45 degrees\n\n30° = Bisect 60°\n45° = Bisect 90°\n\n### 6. Constructing 75 degrees\n\n75° = 45° + 30°, or construct 90° then bisect the remaining 30° space.\n\n## Key Locus Results\n\n**Locus 1**: Fixed distance from a point = CIRCLE with that radius\n\n**Locus 2**: Equidistant from two points A and B = PERPENDICULAR BISECTOR of AB\n\n**Locus 3**: Equidistant from two lines = ANGLE BISECTOR of the angle between them\n\n**Locus 4**: Fixed distance from a line = TWO PARALLEL LINES on either side\n\n**Compound locus**: Intersection of two loci = point(s) satisfying BOTH conditions',
'definitions', 2),

('f09042df-d7a9-46d8-98e9-1a82b5bd8892',
'Worked Examples and Practice: Construction and Loci',
E'## Approach to Construction Questions\n\n### General Rules\n\n1. Always leave construction arcs visible — do NOT erase them. Marks are given for the arcs.\n2. Use sharp pencil for accuracy.\n3. Label all points clearly.\n4. After drawing the construction, answer any measurement questions using a ruler or protractor as directed.\n\n### Example 1: Construct a triangle with sides 6 cm, 5 cm, and 4 cm\n\n1. Draw base AB = 6 cm\n2. Open compass to 5 cm, centre A, draw arc\n3. Open compass to 4 cm, centre B, draw arc\n4. Mark intersection as C\n5. Join AC and BC\nResult: Triangle ABC with required side lengths.\n\n### Example 2: Locate all points 3 cm from point O\n\nThe locus is a circle of radius 3 cm centred at O.\nDraw the circle using compass set to 3 cm.\n\n### Example 3: A dog is tied to a post P by a 5 m rope, and must also stay within 4 m of a gate G. Show the region where the dog can roam.\n\nCircle 1: radius 5 m centred at P (constraint from rope)\nCircle 2: radius 4 m centred at G (constraint from gate)\nThe dog can only be in the INTERSECTION of these two regions.\n\n## Practice Questions\n\n**Q1**: Construct an equilateral triangle of side 5 cm. Measure and write down the height.\n\n**Q2**: Using ruler and compass only, construct angle of 75 degrees.\n\n**Q3**: A point P is equidistant from two fixed points A and B that are 6 cm apart. Describe and draw the locus of P.\n\n**Q4**: Construct a rectangle of length 7 cm and width 4 cm. Draw its diagonals and find their point of intersection. What do you notice?\n\n## Solutions/Guidance\n\n**Q1**: Draw 5 cm base. Open to 5 cm, arcs from both ends — apex C forms equilateral triangle. Height = 5 x sqrt(3)/2 approx 4.33 cm.\n\n**Q2**: Construct 90 degrees, then bisect remaining angle to get 45 degrees. Add 30 degrees (bisect 60 degrees arc). 45 + 30 = 75 degrees.\n\n**Q3**: The locus of P is the perpendicular bisector of segment AB — a straight line perpendicular to AB at its midpoint.\n\n**Q4**: Diagonals of a rectangle bisect each other — they cross at their midpoints, and those midpoints are the same point (the centre of the rectangle).',
'explanation', 3),

('f09042df-d7a9-46d8-98e9-1a82b5bd8892',
'Common Mistakes & Final Exam Practice',
E'## Common Mistakes\n\n1. **Erasing construction arcs**: Never erase your compass arcs. Examiners look for them as proof of correct method. No arcs = no method marks.\n\n2. **Using a protractor for angles when compass is required**: The question says "using ruler and compass only" — this means NO protractor. If you use a protractor, you score zero.\n\n3. **Inaccurate compass settings**: Keep the compass setting fixed throughout each arc. If the radius changes mid-arc, the construction fails.\n\n4. **Wrong locus identification**: "Equidistant from two POINTS" = perpendicular bisector. "Equidistant from two LINES" = angle bisector. These are different.\n\n5. **Missing the intersection region for compound loci**: When two conditions apply, shade the OVERLAP (intersection), not either region separately.\n\n---\n\n## Exam-Standard Construction Question\n\n**Question**: Using ruler and compasses only:\n(a) Construct triangle ABC where AB = 8 cm, BC = 6 cm, angle ABC = 60 degrees.\n(b) Construct the perpendicular bisector of AC.\n(c) Construct the locus of points equidistant from BA and BC.\n(d) Mark the point P which is equidistant from A and C, and also equidistant from BA and BC.\n(e) Measure and state the length AP.\n\n**Guidance**:\n(a) Draw AB = 8 cm. At B, construct 60 degrees. Mark C at 6 cm along the 60 degree ray.\n(b) Perpendicular bisector of AC: arcs from A and C, join intersections.\n(c) Angle bisector of angle ABC: arcs from B cutting BA and BC, then arcs from those points.\n(d) P is at the intersection of the perpendicular bisector of AC and the angle bisector of ABC.\n(e) Measure AP with ruler.',
'practice', 4);
