/*
  # Expand Deep Notes: Topics 18, 19, 20
  
  Topic 18: Binary Operations and Logical Reasoning
  Topic 19: Bearing and Distances
  Topic 20: Transformation Geometry
*/

-- TOPIC 18: Binary Operations
DELETE FROM topic_sections WHERE topic_id = 'd14e7064-c466-47c9-b093-5dc0355a6758';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('d14e7064-c466-47c9-b093-5dc0355a6758',
'Concept Overview: Binary Operations and Logical Reasoning',
E'## What Are Binary Operations?\n\nA **binary operation** is a mathematical rule that takes two elements from a set and combines them to produce a single result. Standard examples are + (addition), - (subtraction), x (multiplication), and / (division). But in WASSCE, you will encounter custom-defined operations.\n\nA binary operation is denoted using symbols like *, #, @, or circle with a dot.\n\n**Example**: Define a * b = 2a + b - ab. Find 3 * 4.\n3 * 4 = 2(3) + 4 - (3)(4) = 6 + 4 - 12 = -2\n\n### Key Properties\n\n**Closure**: Operation * on set S is closed if for all a, b in S, a*b is also in S.\n\n**Commutativity**: a * b = b * a for all a, b\n\n**Associativity**: (a * b) * c = a * (b * c) for all a, b, c\n\n**Identity element**: e such that a * e = e * a = a for all a\n\n**Inverse element**: b is the inverse of a if a * b = b * a = e (identity)\n\n### Cayley Table (Operation Table)\n\nA table showing the result of combining every pair of elements in a set.\nRows represent first element, columns represent second element.\nThe entry in row a and column b gives a * b.',
'overview', 1),

('d14e7064-c466-47c9-b093-5dc0355a6758',
'Definitions and Methods: Binary Operations',
E'## Working With Binary Operations\n\n### Step 1: Understand the Definition\n\nAlways read the definition carefully. The operation is defined by a formula.\n\n**Example**: a # b = 3a - 2b + 1\nThis means: take 3 times first, minus 2 times second, plus 1.\n\n### Step 2: Substitute in Order\n\nNote: a # b and b # a may give different results (not commutative in general).\n5 # 3 = 3(5) - 2(3) + 1 = 15 - 6 + 1 = 10\n3 # 5 = 3(3) - 2(5) + 1 = 9 - 10 + 1 = 0\nSince 5#3 is not equal to 3#5, this operation is NOT commutative.\n\n### Step 3: Testing Properties\n\n**Test for identity e**: Solve a * e = a\nExample with a # b = 3a - 2b + 1:\na # e = a → 3a - 2e + 1 = a → 2e = 2a + 1 → e = a + 1/2\nThis depends on a, so there is NO single identity element.\n\n**Test for commutativity**: Check if a * b = b * a for general a and b (not just specific values)\n\n**Test for associativity**: Compute (a*b)*c and a*(b*c) separately; compare.\n\n### Reading a Cayley Table\n\nFor a * b: look at ROW labelled a, COLUMN labelled b.\n\nExample table for operation # on {1, 2, 3}:\n\n| # | 1 | 2 | 3 |\n| 1 | 2 | 3 | 1 |\n| 2 | 3 | 1 | 2 |\n| 3 | 1 | 2 | 3 |\n\nFrom table: 1#2 = 3 (row 1, column 2)\n2#3 = 2 (row 2, column 3)\n\nIdentity: Row/column where the result equals the header. Row 3 returns 1,2,3 (the set in order) — so 3 is the identity.\n\n### Logical Reasoning (Truth Tables)\n\n**Propositions**: Statements that are either true (T) or false (F).\n\n**NOT p**: negation — if p is T, NOT p is F\n**p AND q**: true only when both are T\n**p OR q**: true when at least one is T\n**p IMPLIES q**: false only when p is T and q is F',
'definitions', 2),

('d14e7064-c466-47c9-b093-5dc0355a6758',
'Worked Examples and Practice: Binary Operations',
E'## Worked Examples\n\n### Example 1: Basic Evaluation\nIf a * b = a^2 - 2b, find: (a) 3*4, (b) 4*3, (c) (2*1)*3\n\n(a) 3*4 = 9 - 8 = 1\n(b) 4*3 = 16 - 6 = 10\n(c) First find 2*1 = 4 - 2 = 2; then 2*3 = 4 - 6 = -2\n\n### Example 2: Finding Unknown\nIf a * b = 2a + 3b, find x given that x * 3 = 25.\n\n2x + 9 = 25\n2x = 16\nx = 8\n\n### Example 3: Identity Element\nFor a * b = ab + a + b, find the identity element.\n\nNeed a * e = a:\nae + a + e = a\nae + e = 0\ne(a + 1) = 0\ne = 0 (for all a not equal to -1)\n\nVerify: a * 0 = 0 + a + 0 = a ✓ So e = 0 is the identity.\n\n### Example 4: Cayley Table\nGiven the table, determine if the operation is commutative.\n\n| * | a | b | c |\n| a | b | c | a |\n| b | c | a | b |\n| c | a | b | c |\n\nCheck: a*b = c (row a, col b); b*a = c (row b, col a). Equal here.\nCheck: a*c = a (row a, col c); c*a = a (row c, col a). Equal here.\nAll entries across the main diagonal are symmetric, so YES, commutative.\n\n---\n\n## Practice Questions\n\n**Q1**: If p * q = p^2 + q - pq, find: (a) 2*3 (b) 3*2 (c) Is it commutative?\n\n**Q2**: Define x # y = 2xy - x - y. Find the value of y if 3 # y = 11.\n\n**Q3**: For a * b = (a+b)/2, show this operation is commutative.\n\n**Q4**: An operation @ is defined on positive integers by a @ b = HCF(a, b). Find: (a) 12@8, (b) 15@25. Is this commutative?\n\n---\n\n## Solutions\n\n**Q1**: (a) 4+3-6=1 (b) 9+2-6=5 (c) Not commutative since 2*3=1 but 3*2=5\n\n**Q2**: 2(3)(y) - 3 - y = 11; 6y - y = 14; 5y = 14; y = 14/5 = 2.8\n\n**Q3**: a*b = (a+b)/2 = (b+a)/2 = b*a. Since addition is commutative, so is this operation. ✓\n\n**Q4**: (a) HCF(12,8) = 4 (b) HCF(15,25) = 5. Commutative since HCF(a,b) = HCF(b,a) always.',
'explanation', 3),

('d14e7064-c466-47c9-b093-5dc0355a6758',
'Common Mistakes & Final Practice',
E'## Common Mistakes\n\n1. **Substituting in wrong order**: In a*b = f(a,b), always put the FIRST operand where a appears and SECOND where b appears. a*b and b*a can differ.\n\n2. **Assuming commutativity**: Do not assume a*b = b*a. Always test explicitly.\n\n3. **Identity element confusion**: The identity element makes a*e = a. Do not confuse with inverse (which gives the identity result).\n\n4. **Not verifying both sides for identity**: For identity e, you must check BOTH a*e = a AND e*a = a.\n\n5. **Cayley table reading error**: Row first, then column. a*b means go to row a, find column b.\n\n---\n\n## Exam Questions\n\n**Question 1**: An operation * is defined on real numbers by a * b = a + b - ab.\n(a) Find 2 * 3\n(b) Find the identity element\n(c) Is the operation commutative? Justify.\n(d) Find the inverse of 4 under this operation.\n\n**Question 2**: The operation # on the set S = {1, 2, 3, 4} is partially shown:\n\n| # | 1 | 2 | 3 | 4 |\n| 1 | 1 | 2 | 3 | 4 |\n| 2 | 2 | 4 | 1 | 3 |\n| 3 | 3 | 1 | 4 | 2 |\n| 4 | 4 | 3 | 2 | 1 |\n\nFrom the table: (a) Find 2#3 and 3#2. (b) Identify the identity element. (c) Find the inverse of 3.\n\n---\n\n## Solutions\n\n**Q1**: (a) 2+3-6 = -1\n(b) a*e = a: a+e-ae=a; e(1-a)=0; e=0\nVerify: a*0 = a+0-0 = a ✓; e=0\n(c) a*b = a+b-ab; b*a = b+a-ba = a+b-ab. Equal, so commutative.\n(d) 4*x = e = 0: 4+x-4x=0; 4-3x=0; x=4/3. Inverse of 4 is 4/3.\n\n**Q2**: (a) 2#3 = 1 (row 2, col 3); 3#2 = 1 (row 3, col 2). Equal here.\n(b) Identity: row 1 gives back 1,2,3,4 in order and column 1 gives 1,2,3,4 — identity is 1.\n(c) 3#x = 1 (identity); from row 3: 3#4 = 2, 3#2 = 1. So inverse of 3 is 2.',
'practice', 4);


-- TOPIC 19: Bearing and Distances
DELETE FROM topic_sections WHERE topic_id = '070d2bf3-3eb3-45d2-b9c3-0476f6632897';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('070d2bf3-3eb3-45d2-b9c3-0476f6632897',
'Concept Overview: Bearing and Distances',
E'## What Is a Bearing?\n\nA **bearing** is a direction measured as an angle in degrees, always:\n1. Starting from North\n2. Measured clockwise\n3. Given as a THREE-digit number (e.g., 045°, not 45°)\n\nBearings range from 000° to 360°.\n\n### Why Three Digits?\n\nUsing three digits prevents ambiguity:\n- 045° means 45° clockwise from North (NE direction)\n- 090° = Due East\n- 180° = Due South\n- 270° = Due West\n- 360° = 000° = Due North\n\n### Connection to Trigonometry\n\nMost bearing problems require the Sine Rule, Cosine Rule, or right-triangle trigonometry. The bearing gives the DIRECTION; you then use geometry to find DISTANCES.\n\n### Common Bearing Problems in WASSCE\n\n1. Finding distance between two points given bearings\n2. Finding the bearing of one point from another\n3. Navigation problems (ships, planes, walkers)\n4. Problems combining two or more journeys\n5. Reverse bearing (back bearing)',
'overview', 1),

('070d2bf3-3eb3-45d2-b9c3-0476f6632897',
'Definitions and Key Concepts: Bearings',
E'## All Key Terms and Techniques\n\n### Cardinal and Intercardinal Directions\n\n| Direction | Bearing |\n| North (N) | 000 |\n| North-East (NE) | 045 |\n| East (E) | 090 |\n| South-East (SE) | 135 |\n| South (S) | 180 |\n| South-West (SW) | 225 |\n| West (W) | 270 |\n| North-West (NW) | 315 |\n\n### Back Bearing (Reverse Bearing)\n\nIf the bearing from A to B is X, then the bearing from B to A is:\n- Back bearing = X + 180° if X < 180°\n- Back bearing = X - 180° if X >= 180°\n\nExample: Bearing from A to B = 060°. Back bearing (B to A) = 060 + 180 = 240°.\n\n### Setting Up Triangles from Bearings\n\n1. Always draw a sketch with North arrows at each point\n2. Mark the bearing angles measured clockwise from North\n3. Identify the interior angle of the triangle formed\n4. Apply trigonometry (right-angle, Sine Rule, or Cosine Rule)\n\n### Interior Angle from Bearings\n\nWhen two bearings meet at a point, the interior angle of the triangle often requires careful calculation:\n- Draw North direction at the relevant point\n- The bearing IS the clockwise angle from North\n- The interior angle = related angle based on the geometry\n\n**Key result**: If bearing of B from A = 060° and bearing of C from A = 130°, the angle BAC = 130 - 60 = 70°.\n\nIf the bearings are on opposite sides of North:\nAngle BAC = bearing of C + (360 - bearing of B) or other combinations depending on position.',
'definitions', 2),

('070d2bf3-3eb3-45d2-b9c3-0476f6632897',
'Worked Examples and Practice: Bearings',
E'## Worked Examples\n\n### Example 1: Basic bearing problem\nA ship sails 20 km on bearing 040° then 15 km on bearing 130°. Find the distance from the starting point.\n\nStep 1: The angle between the two directions = 130 - 40 = 90°\n(The two legs are perpendicular!)\n\nStep 2: Distance = sqrt(20^2 + 15^2) = sqrt(400 + 225) = sqrt(625) = 25 km\n\n**Answer: 25 km**\n\n---\n\n### Example 2: Finding a bearing\nPoint B is 8 km East and 6 km North of point A. Find the bearing of B from A.\n\nStep 1: Draw the right triangle. The North-South component = 6 (North), East-West = 8 (East).\n\nStep 2: tan(theta) = 8/6 = 4/3; theta = tan^(-1)(4/3) = 53.1°\n\nStep 3: Bearing is measured from North clockwise. theta is the angle from North toward East.\n\nBearing = 053.1° (approx 053°)\n\n---\n\n### Example 3: Back bearing\nThe bearing of town Q from town P is 125°. What is the bearing of P from Q?\n\nBack bearing = 125 + 180 = 305°\n\n**Answer: 305°**\n\n---\n\n### Example 4: Non-right triangle (Sine/Cosine Rule)\nFrom port P, a ship sails 40 km on bearing 070° to reach point A. From A, it sails on bearing 160° to reach point B which is 30 km from A. Find the distance PB.\n\nStep 1: At A, the angle between the two directions (PA extended and AB).\nPA direction = 070° (measured from North at P). So at A, the ship came from 070+180=250° (back bearing).\nAB direction = 160°.\nAngle at A = 250 - 160 = 90°\n\nStep 2: PB^2 = PA^2 + AB^2 = 1600 + 900 = 2500\nPB = 50 km\n\n**Answer: PB = 50 km**\n\n---\n\n## Practice Questions\n\n**Q1**: A man walks 5 km due North then 12 km due East. Find his distance from the start and the bearing of his final position from the start.\n\n**Q2**: Two ships leave port at the same time. Ship A sails on bearing 030° at 20 km/h. Ship B sails on bearing 150° at 15 km/h. After 2 hours, find the distance between them.\n\n**Q3**: P is 10 km from Q on bearing 045°. R is 8 km from Q on bearing 315°. Find the distance PR.\n\n---\n\n## Solutions\n\n**Q1**: Distance = sqrt(25+144) = sqrt(169) = 13 km\ntan(theta) = 12/5 = 2.4; theta = 67.4°. Bearing = 0 + 67.4 = 067.4° ≈ 067°\n\n**Q2**: After 2 hours: Ship A = 40 km on 030°; Ship B = 30 km on 150°\nAngle between them = 150 - 30 = 120°\nd^2 = 40^2 + 30^2 - 2(40)(30)cos(120°) = 1600+900-2400(-0.5) = 2500+1200 = 3700\nd = sqrt(3700) ≈ 60.8 km\n\n**Q3**: Angle PQR = 315 - 45 = 270°? No — angle from 045 to 315 going clockwise = 270°, but the interior angle = 360-270 = 90°. Actually: 045° is NE and 315° is NW. Angle between = 315-45 = 270° going clockwise, or 360-270 = 90° going counterclockwise. Interior angle = 90°.\nPR^2 = 10^2 + 8^2 = 164; PR = sqrt(164) = 2sqrt(41) ≈ 12.8 km',
'explanation', 3),

('070d2bf3-3eb3-45d2-b9c3-0476f6632897',
'Common Mistakes & Exam Questions: Bearings',
E'## Common Mistakes\n\n1. **Not writing three digits**: Always write bearings as three digits: 060°, not 60°. This is a standard requirement in WASSCE.\n\n2. **Measuring from wrong direction**: Bearings are ALWAYS from North, ALWAYS clockwise. Never measure from South or East.\n\n3. **Wrong interior angle**: The interior angle of the triangle is NOT always equal to the difference in bearings. Draw careful sketches with North arrows at EACH point.\n\n4. **Back bearing error**: If bearing A to B = 250°, back bearing = 250 - 180 = 070°. Students sometimes add 180 when they should subtract.\n\n5. **Forgetting units**: Always state km, m, or whatever unit the problem uses.\n\n---\n\n## Exam-Standard Questions\n\n**Question 1**: Three towns P, Q, R are such that Q is 50 km from P on bearing 060°, and R is 30 km from P on bearing 150°. Find:\n(a) The distance QR\n(b) The bearing of R from Q\n(c) The bearing of Q from R\n\n**Question 2**: A boat leaves port A and travels 15 km on bearing 035° to reach point B. It then changes course and travels 20 km on bearing 305° to reach point C. Find:\n(a) The distance AC\n(b) The bearing of C from A\n\n---\n\n## Solutions\n\n**Q1**: Angle QPR = 150 - 60 = 90°\n(a) QR^2 = 50^2 + 30^2 = 2500+900 = 3400; QR = sqrt(3400) = 10sqrt(34) ≈ 58.3 km\n(b) In triangle PQR, angle at P = 90°.\ntan(angle PQR) = PR/PQ = 30/50 = 0.6; angle PQR = 31°\nBearing of R from Q: Q is NE of P. Looking from Q back to P, bearing is 060+180=240°.\nFrom Q, R is at 240° + (90°+31°) adjustment... Draw carefully.\nActually: bearing from Q to R = bearing from Q to P + angle = (240°) then rotate toward R.\nAngle at Q in triangle = arctan(30/50) from the right angle... Full working needs careful sketch.\n\n**Q2**: Angle at B between directions: bearing AB = 035; back bearing from B = 035+180=215. Direction BC = 305.\nAngle ABC = 305-215 = 90°\n(a) AC^2 = 15^2 + 20^2 = 225+400 = 625; AC = 25 km\n(b) In triangle ABC (right angle at B): tan(angle BAC) = BC/AB = 20/15 = 4/3; angle = 53.1°\nBearing of A to B = 035°; bearing of A to C = 035 + 53.1 = 088.1° ≈ 088°',
'practice', 4);


-- TOPIC 20: Transformation Geometry
DELETE FROM topic_sections WHERE topic_id = 'be4ac0b9-9854-4e1f-a7c3-6785aca9e7f0';

INSERT INTO topic_sections (topic_id, title, content, section_type, order_index) VALUES
('be4ac0b9-9854-4e1f-a7c3-6785aca9e7f0',
'Concept Overview: Transformation Geometry',
E'## What Is Transformation Geometry?\n\nA **transformation** moves, flips, or resizes a geometric shape. The original shape is called the **object** and the result is the **image**.\n\nIn WASSCE, transformations carry 10-15 marks in the theory paper and involve both graphical and algebraic work.\n\n### Four Types of Transformation\n\n1. **Translation** — slides the shape (no rotation, no size change)\n2. **Reflection** — flips the shape across a line (mirror image)\n3. **Rotation** — turns the shape about a fixed point\n4. **Enlargement** — scales the shape up or down from a centre\n\n### Key Vocabulary\n\n**Object**: The original shape (labelled A, B, C)\n**Image**: The transformed shape (labelled A, B, C with primes: A\', B\', C\')\n**Invariant point**: A point that does not move under the transformation\n**Congruent shapes**: Same size and shape (translation, reflection, rotation)\n**Similar shapes**: Same shape, different size (enlargement)\n**Scale factor**: The ratio of image length to object length in enlargement',
'overview', 1),

('be4ac0b9-9854-4e1f-a7c3-6785aca9e7f0',
'All Transformation Types: Rules and Methods',
E'## Transformation Rules\n\n### 1. Translation\n\nA translation moves every point the same distance in the same direction.\nRepresented by a vector (a; b): moves a units right and b units up (negative = left/down).\n\nIf A = (x, y), then A\' = (x+a, y+b)\n\n**Example**: Translate triangle ABC by vector (3; -2):\nA(1,4) → A\'(4,2); B(3,6) → B\'(6,4); C(5,4) → C\'(8,2)\n\n### 2. Reflection\n\nA reflection flips the shape across a mirror line. Each point is the same perpendicular distance from the mirror as its image.\n\n**Common mirror lines**:\n\n| Mirror Line | Rule for (x,y) → image |\n| x-axis (y=0) | (x, y) → (x, -y) |\n| y-axis (x=0) | (x, y) → (-x, y) |\n| y = x | (x, y) → (y, x) |\n| y = -x | (x, y) → (-y, -x) |\n| y = k (horizontal) | (x, y) → (x, 2k-y) |\n| x = k (vertical) | (x, y) → (2k-x, y) |\n\n### 3. Rotation\n\nA rotation turns the shape through an angle about a fixed point (centre of rotation).\n\n**About the origin**:\n\n| Angle | (x,y) → image |\n| 90° anticlockwise | (x, y) → (-y, x) |\n| 90° clockwise | (x, y) → (y, -x) |\n| 180° (either) | (x, y) → (-x, -y) |\n| 270° anticlockwise | (x, y) → (y, -x) (same as 90° CW) |\n\nFor rotation about other centres: translate so centre is at origin, rotate, translate back.\n\n### 4. Enlargement\n\nAn enlargement scales the shape by a scale factor k from a centre of enlargement.\n\nIf centre is O and scale factor is k:\n- For each point P, the image P\' is on ray OP\n- OP\' = k × OP\n\n**Formula** (if centre is origin): (x, y) → (kx, ky)\n\n**For centre (a,b)**: translate centre to origin, scale, translate back:\nA\' = (a + k(x-a), b + k(y-b))\n\n**Scale factor k**:\n- k > 1: enlargement (bigger)\n- 0 < k < 1: reduction (smaller)\n- k < 0: enlargement through the centre (inverted image)',
'definitions', 2),

('be4ac0b9-9854-4e1f-a7c3-6785aca9e7f0',
'Worked Examples: Transformation Geometry',
E'## Worked Examples\n\n### Example 1: Translation\nTranslate A(2, -1), B(4, 3) by vector (-3; 2).\n\nA\' = (2+(-3), -1+2) = (-1, 1)\nB\' = (4+(-3), 3+2) = (1, 5)\n\n**Answers: A\'(-1, 1), B\'(1, 5)**\n\n---\n\n### Example 2: Reflection in the line y = x\n\nReflect P(3, 7) in the line y = x.\n\nRule: (x, y) → (y, x)\nP\' = (7, 3)\n\n**Answer: P\'(7, 3)**\n\n---\n\n### Example 3: Rotation 90° anticlockwise about origin\n\nRotate triangle A(1,0), B(3,0), C(3,2) by 90° anticlockwise about origin.\n\nRule: (x,y) → (-y, x)\nA\' = (0, 1)\nB\' = (0, 3)\nC\' = (-2, 3)\n\n**Answers: A\'(0,1), B\'(0,3), C\'(-2,3)**\n\n---\n\n### Example 4: Enlargement from origin, scale factor 3\n\nEnlarge P(2, 1), Q(4, 1), R(4, 3) by scale factor 3 from origin.\n\nP\' = (6, 3)\nQ\' = (12, 3)\nR\' = (12, 9)\n\nVerify: Each length is multiplied by 3.\nPQ = 2 units; P\'Q\' = 6 units. Ratio = 3. ✓\n\n---\n\n### Example 5: Enlargement from non-origin centre\n\nEnlarge A(1, 2) by scale factor 2 from centre C(3, 4).\n\nA\' = (3 + 2(1-3), 4 + 2(2-4))\n= (3 + 2(-2), 4 + 2(-2))\n= (3-4, 4-4)\n= (-1, 0)\n\n**Answer: A\'(-1, 0)**\n\n---\n\n### Example 6: Finding the transformation\n\nObject: A(1,2), B(3,2), C(3,4). Image: A\'(2,1), B\'(2,3), C\'(4,3).\nDescribe the transformation fully.\n\nCheck translation: A to A\' = (1,−1). Check B: B + (1,-1) = (4,1) ≠ B\'(2,3). NOT a translation.\nCheck reflection in y=x: (x,y)→(y,x). A(1,2)→(2,1)=A\' ✓; B(3,2)→(2,3)=B\' ✓; C(3,4)→(4,3)=C\' ✓\n\n**Answer: Reflection in the line y = x**\n\n---\n\n## Practice Questions\n\n**Q1**: Translate A(3,5) by (-2; 4) then reflect the image in the x-axis. Find the final position.\n\n**Q2**: Rotate P(4,0), Q(4,4), R(0,4) by 90° clockwise about the origin. State the image coordinates.\n\n**Q3**: Enlarge triangle with vertices (1,1), (3,1), (3,3) by scale factor 1/2 from centre (1,1). Find image vertices.\n\n**Q4**: Describe fully the transformation mapping A(2,3) to A\'(6,9), B(4,1) to B\'(12,3).\n\n---\n\n## Solutions\n\n**Q1**: After translation: A\'(1,9). After reflection in x-axis: (x,y)→(x,-y): A\'\'(1,-9)\n\n**Q2**: Rule 90° CW: (x,y)→(y,-x)\nP\'(0,-4); Q\'(4,-4); R\'(4,0)\n\n**Q3**: Centre (1,1), k=1/2:\nFor (1,1): image = (1+0.5(0), 1+0.5(0)) = (1,1) — invariant (it is the centre)\nFor (3,1): image = (1+0.5(2), 1+0.5(0)) = (2,1)\nFor (3,3): image = (1+0.5(2), 1+0.5(2)) = (2,2)\n\n**Q4**: A→A\': (2,3)→(6,9). Ratio: 6/2=3, 9/3=3. Scale factor = 3.\nCheck B: (4,1)→(12,3). 12/4=3, 3/1=3. ✓\nCentre: On line from A through A\'. x=2+t(4), y=3+t(6). For origin: t=-0.5 → centre (0,0).\nAnswer: Enlargement, centre origin, scale factor 3.',
'explanation', 3),

('be4ac0b9-9854-4e1f-a7c3-6785aca9e7f0',
'Common Mistakes & Exam-Standard Practice',
E'## Common Mistakes\n\n1. **Mixing up clockwise and anticlockwise rotation rules**: 90° anticlockwise: (x,y)→(-y,x). 90° clockwise: (x,y)→(y,-x). Learn both — they are frequently confused.\n\n2. **Reflection rule errors for y=x vs y=-x**: y=x gives (x,y)→(y,x) (swap). y=-x gives (x,y)→(-y,-x) (swap AND negate).\n\n3. **Enlargement with negative scale factor**: Negative scale factor means the image is on the OPPOSITE side of the centre. Use the formula carefully.\n\n4. **Not labelling image correctly**: Always use prime notation: A\', B\', C\'. Match labels to the original.\n\n5. **Forgetting to verify your transformation description**: After identifying a transformation, check it works for ALL vertices, not just one.\n\n---\n\n## Exam-Standard Questions\n\n**Question 1**: On a coordinate grid, plot triangle ABC with A(1,1), B(4,1), C(4,3).\n(a) Reflect ABC in the line x = 2. Label image A\'B\'C\'.\n(b) Rotate A\'B\'C\' by 90° anticlockwise about the origin. Label image A\'\'B\'\'C\'\'.\n(c) Describe fully the single transformation mapping ABC to A\'\'B\'\'C\'\'.\n\n**Question 2**: An enlargement with centre E(2,0) maps P(4,2) to P\'(8,4). Find:\n(a) The scale factor\n(b) The image of Q(0,4) under the same enlargement\n(c) The area ratio of object to image\n\n---\n\n## Solutions\n\n**Q1**: Reflection in x=2: rule (x,y)→(4-x, y)\nA\'(3,1), B\'(0,1), C\'(0,3)\n\nRotate A\'B\'C\' by 90° anticlockwise: (x,y)→(-y,x)\nA\'\'(-1,3), B\'\'(-1,0), C\'\'(-3,0)\n\n(c) Check: A(1,1)→A\'\'(-1,3).\nFrom A(1,1) to A\'\'(-1,3): change is (-2,2).\nFrom B(4,1) to B\'\'(-1,0): change is (-5,-1). Not uniform → not translation.\nCheck rotation 90° anticlockwise about some centre (a,b):\n(x-a,y-b)→(-(y-b),x-a): -1-a = -(1-b), 3-b = 1-a\nFrom first: -1-a = -1+b → -a = b → a+b=0\nFrom second: 3-b = 1-a → a-b = -2\nAdding: 2a = -2; a=-1; b=1. Centre (-1,1).\nVerify with C(4,3): (4-(-1),3-1)=(5,2)→rotate→(-2,5); +centre(-1,1)=(-3,6)... check C\'\'(-3,0). Does not match.\nFull answer: it is a composite of reflection then rotation — describe as two separate transformations or find the equivalent single one by coordinate analysis.\n\n**Q2**: (a) EP = (4-2,2-0)=(2,2); EP\' = (8-2,4-0)=(6,4). Scale = 6/2 = 4/2 = ... EP\'=3*EP. k=3.\n(b) Q\' = (2+3(0-2), 0+3(4-0)) = (2-6, 12) = (-4, 12)\n(c) Area ratio = k^2 = 9. Image area is 9 times object area.',
'practice', 4);
